### PR TITLE
Bug 1744105 - Please update Phabricator to 2021 Week 49 (20211202.1)

### PR DESCRIPTION
**Pull request by dklawren**

### CODE REVIEW

**Comment by betterphp** [comment]
Would be great to have this merged. We're currently planning to migrate to using phabricator from this repo after the phacility one was marked EOL but as this is a bit behind we're stuck.

**Comment by dklawren** [comment]
> Would be great to have this merged. We're currently planning to migrate to using phabricator from this repo after the phacility one was marked EOL but as this is a bit behind we're stuck.

Sure. We go through a pretty thorough QA process with each release which we doing currently on our devel instance. Once we work out a few bugs with our extensions, we will be merging this and deploying to production.

**Comment by betterphp** [comment]
Awesome. I'll keep an eye on this pull then.

**Comment by betterphp** [comment]
<3

**Pull request merged**
